using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace SharedKernel.Presentation.WebApi.Generators.Tests;

/// <summary>
/// P-563 P2: the generator finds every <c>IEndpointModule</c> of the compilation and emits one <c>MapEndpoints()</c>
/// that calls them in ordinal full-name order, reports a module it cannot call, and emits nothing when there is
/// nothing to map.
/// </summary>
public sealed class EndpointModuleGeneratorTests
{
    private const string Usings = """
        using Microsoft.AspNetCore.Builder;
        using Microsoft.AspNetCore.Routing;
        using SharedKernel.Presentation.WebApi;
        """;

    [Fact]
    public void One_module_is_mapped_and_the_result_compiles()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            namespace Billing;

            public sealed class InvoiceEndpoints : IEndpointModule
            {
                public static void Map(IEndpointRouteBuilder app) => app.MapGet("/invoices", () => "ok");
            }
            """);

        outcome.GeneratorDiagnostics.Should().BeEmpty();
        outcome.CompilationErrors.Should().BeEmpty();
        outcome.Generated.Should().Contain("global::Billing.InvoiceEndpoints.Map(app);")
            .And.Contain("// <auto-generated/>")
            .And.Contain("#nullable enable")
            .And.Contain("[global::System.CodeDom.Compiler.GeneratedCode(\"SharedKernel.Presentation.WebApi.Generators\"")
            .And.Contain("internal static partial class EndpointModuleMappingExtensions")
            .And.Contain("public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapEndpoints(this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder app)");
    }

    [Fact]
    public void Modules_are_called_in_ordinal_full_name_order_across_files()
    {
        var outcome = GeneratorHarness.Run(
            true,
            Usings + """

            namespace Zeta { public sealed class A : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } } }
            namespace alpha { public sealed class Z : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } } }
            """,
            Usings + """

            namespace Alpha
            {
                public sealed class Orders : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
                internal sealed class Customers : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
                public static class Outer
                {
                    internal struct Nested : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
                }
            }
            """);

        outcome.GeneratorDiagnostics.Should().BeEmpty();
        outcome.CompilationErrors.Should().BeEmpty();

        var calls = outcome.Generated!.Split('\n').Select(line => line.Trim()).Where(line => line.EndsWith(".Map(app);", StringComparison.Ordinal)).ToArray();
        calls.Should().Equal(
            "global::Alpha.Customers.Map(app);",
            "global::Alpha.Orders.Map(app);",
            "global::Alpha.Outer.Nested.Map(app);",
            "global::Zeta.A.Map(app);",
            "global::alpha.Z.Map(app);");
    }

    [Fact]
    public void A_partial_module_is_mapped_once()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            public sealed partial class Split : IEndpointModule { }
            public sealed partial class Split : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
            """);

        outcome.CompilationErrors.Should().BeEmpty();
        outcome.Generated!.Split("global::Split.Map(app);").Should().HaveCount(2);
    }

    [Fact]
    public void An_explicitly_implemented_map_is_called_through_the_interface()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            public sealed class Hidden : IEndpointModule
            {
                static void IEndpointModule.Map(IEndpointRouteBuilder app) { }
            }
            """);

        outcome.GeneratorDiagnostics.Should().BeEmpty();
        outcome.CompilationErrors.Should().BeEmpty();
        outcome.Generated.Should().Contain("MapModule<global::Hidden>(app);").And.Contain("private static void MapModule<TModule>");
    }

    [Fact]
    public void Nothing_is_generated_without_modules()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            public sealed class NotAModule { public static void Map(IEndpointRouteBuilder app) { } }
            public interface IMoreSpecificModule : IEndpointModule { }
            """);

        outcome.Generated.Should().BeNull();
        outcome.GeneratorDiagnostics.Should().BeEmpty();
    }

    [Fact]
    public void Nothing_is_generated_when_webapi_is_not_referenced()
    {
        // A look-alike interface declared in the compilation itself is not WebApi's.
        var outcome = GeneratorHarness.Run(false, """
            namespace SharedKernel.Presentation.WebApi
            {
                public interface IEndpointModule { static abstract void Map(object app); }
            }

            public sealed class LookAlike : SharedKernel.Presentation.WebApi.IEndpointModule
            {
                public static void Map(object app) { }
            }
            """);

        outcome.Generated.Should().BeNull();
        outcome.GeneratorDiagnostics.Should().BeEmpty();
        outcome.CompilationErrors.Should().BeEmpty();
    }

    [Fact]
    public void An_abstract_module_is_reported_and_not_called()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            public abstract class Base : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
            """);

        var diagnostic = outcome.GeneratorDiagnostics.Should().ContainSingle().Subject;
        diagnostic.Id.Should().Be("SKEP001");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Error);
        diagnostic.GetMessage().Should().StartWith("Endpoint module 'Base' is abstract");
        diagnostic.Location.GetLineSpan().StartLinePosition.Line.Should().Be(3);
        outcome.Generated.Should().NotContain("Base.Map");
        outcome.CompilationErrors.Should().BeEmpty("MapEndpoints() is still generated, so the call site does not fail as well");
    }

    [Fact]
    public void A_generic_module_is_reported()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            public sealed class Generic<T> : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
            """);

        var diagnostic = outcome.GeneratorDiagnostics.Should().ContainSingle().Subject;
        diagnostic.Id.Should().Be("SKEP002");
        diagnostic.GetMessage().Should().StartWith("Endpoint module 'Generic<T>' is generic");
        outcome.Generated.Should().NotContain("Generic");
    }

    [Fact]
    public void A_module_nested_in_a_generic_type_is_reported()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            public sealed class Outer<T>
            {
                public sealed class Inner : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
            }
            """);

        var diagnostic = outcome.GeneratorDiagnostics.Should().ContainSingle().Subject;
        diagnostic.Id.Should().Be("SKEP002");
        diagnostic.GetMessage().Should().Contain("is nested in the generic type 'Outer<T>'");
    }

    [Theory]
    [InlineData("private", "it is private")]
    [InlineData("protected", "it is protected")]
    [InlineData("private protected", "it is private protected")]
    public void A_module_the_assembly_cannot_reach_is_reported(string accessibility, string reason)
    {
        var outcome = GeneratorHarness.Run(sources: Usings + $$"""

            public class Host
            {
                {{accessibility}} sealed class Hidden : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
            }
            """);

        var diagnostic = outcome.GeneratorDiagnostics.Should().ContainSingle().Subject;
        diagnostic.Id.Should().Be("SKEP003");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Error);
        diagnostic.GetMessage().Should().Contain($"'Host.Hidden' cannot be reached by the generated MapEndpoints(): {reason}");
        outcome.CompilationErrors.Should().BeEmpty();
    }

    [Fact]
    public void A_module_inside_a_private_type_is_reported()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            public class Host
            {
                private static class Group
                {
                    public sealed class Visible : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
                }
            }
            """);

        var diagnostic = outcome.GeneratorDiagnostics.Should().ContainSingle().Subject;
        diagnostic.Id.Should().Be("SKEP003");
        diagnostic.GetMessage().Should().Contain("the type 'Host.Group' it is nested in is private");
    }

    [Fact]
    public void A_file_local_module_is_reported()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            file sealed class Local : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
            """);

        var diagnostic = outcome.GeneratorDiagnostics.Should().ContainSingle().Subject;
        diagnostic.Id.Should().Be("SKEP003");
        diagnostic.GetMessage().Should().Contain("it is file-local");
        outcome.CompilationErrors.Should().BeEmpty();
    }

    [Fact]
    public void A_type_that_inherits_map_from_another_module_is_warned_about_and_not_mapped_twice()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            public class Orders : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
            public sealed class SpecialOrders : Orders { }
            """);

        var diagnostic = outcome.GeneratorDiagnostics.Should().ContainSingle().Subject;
        diagnostic.Id.Should().Be("SKEP004");
        diagnostic.Severity.Should().Be(DiagnosticSeverity.Warning);
        diagnostic.GetMessage().Should().StartWith("'SpecialOrders' inherits Map from the endpoint module 'Orders'");
        outcome.Generated.Should().Contain("global::Orders.Map(app);").And.NotContain("SpecialOrders");
    }

    [Fact]
    public void A_type_that_does_not_implement_map_is_left_to_the_compiler()
    {
        var outcome = GeneratorHarness.Run(sources: Usings + """

            public sealed class Broken : IEndpointModule { }
            """);

        outcome.GeneratorDiagnostics.Should().BeEmpty();
        outcome.Generated.Should().BeNull();
        outcome.CompilationErrors.Should().ContainSingle(error => error.Id == "CS0535");
    }

    [Fact]
    public void An_unrelated_edit_reuses_the_cached_output()
    {
        var compilation = GeneratorHarness.Compile(true, Usings + """

            public sealed class Orders : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }
            """);

        var driver = GeneratorHarness.CreateDriver().RunGenerators(compilation);

        var edited = compilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText(
            "public static class Unrelated { public static int Answer => 42; }", GeneratorHarness.ParseOptions, path: "Unrelated.cs"));
        var result = driver.RunGenerators(edited).GetRunResult().Results.Single();

        result.TrackedSteps[EndpointModuleGenerator.TrackingNames.Modules]
            .SelectMany(step => step.Outputs)
            .Should().OnlyContain(output => output.Reason == IncrementalStepRunReason.Cached || output.Reason == IncrementalStepRunReason.Unchanged);
        result.TrackedOutputSteps.SelectMany(step => step.Value).SelectMany(step => step.Outputs)
            .Should().OnlyContain(output => output.Reason == IncrementalStepRunReason.Cached || output.Reason == IncrementalStepRunReason.Unchanged);
    }

    [Fact]
    public void Editing_a_module_body_does_not_change_the_output()
    {
        const string before = "public sealed class Orders : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { } }";
        const string after = "public sealed class Orders : IEndpointModule { public static void Map(IEndpointRouteBuilder app) { _ = app; } }";

        var compilation = GeneratorHarness.Compile(true, Usings + before);
        var driver = GeneratorHarness.CreateDriver().RunGenerators(compilation);

        var oldTree = compilation.SyntaxTrees.Single();
        var edited = compilation.ReplaceSyntaxTree(oldTree, CSharpSyntaxTree.ParseText(Usings + after, GeneratorHarness.ParseOptions, path: oldTree.FilePath));
        var result = driver.RunGenerators(edited).GetRunResult().Results.Single();

        result.TrackedSteps[EndpointModuleGenerator.TrackingNames.Candidates]
            .SelectMany(step => step.Outputs)
            .Should().OnlyContain(output => output.Reason == IncrementalStepRunReason.Unchanged || output.Reason == IncrementalStepRunReason.Cached);
        result.TrackedOutputSteps.SelectMany(step => step.Value).SelectMany(step => step.Outputs)
            .Should().OnlyContain(output => output.Reason == IncrementalStepRunReason.Cached || output.Reason == IncrementalStepRunReason.Unchanged);
    }
}
