using FluentAssertions;
using SharedKernel.Domain.Events;

namespace SharedKernel.Domain.Tests;

public class DomainEventTests
{
    private sealed record TestEvent : DomainEvent
    {
        public string Payload { get; init; } = string.Empty;
    }

    [Fact]
    public void DomainEvent_Id_GeneratedOnConstruction()
    {
        var evt = new TestEvent { OccurredOn = DateTimeOffset.UtcNow };
        evt.Id.Should().NotBeEmpty();
    }

    [Fact]
    public void DomainEvent_TwoInstances_HaveDifferentIds()
    {
        var now = DateTimeOffset.UtcNow;
        var a = new TestEvent { OccurredOn = now };
        var b = new TestEvent { OccurredOn = now };
        a.Id.Should().NotBe(b.Id);
    }

    [Fact]
    public void DomainEvent_OccurredOn_ReturnsSuppliedValue()
    {
        var time = new DateTimeOffset(2026, 5, 22, 10, 30, 0, TimeSpan.Zero);
        var evt = new TestEvent { OccurredOn = time };
        evt.OccurredOn.Should().Be(time);
    }

    [Fact]
    public void DomainEvent_ImplementsIDomainEvent()
    {
        var evt = new TestEvent { OccurredOn = DateTimeOffset.UtcNow };
        evt.Should().BeAssignableTo<IDomainEvent>();
    }

    [Fact]
    public void DomainEvent_RecordEquality_SameValues_Equal()
    {
        var id = Guid.NewGuid();
        var time = DateTimeOffset.UtcNow;
        // Records use value equality on all properties
        // Since Id is auto-generated and unique per instance we verify the OccurredOn is preserved
        var evt = new TestEvent { OccurredOn = time, Payload = "test" };
        evt.OccurredOn.Should().Be(time);
        evt.Payload.Should().Be("test");
    }

    // --- T-14: DomainEvent<TPayload> (P-039/WO-009) ---

    private sealed record OrderPlacedPayload(Guid OrderId, decimal Total);

    private sealed record OrderPlacedEvent : DomainEvent<OrderPlacedPayload>;

    [Fact]
    public void DomainEventT_Payload_ExposedCorrectly()
    {
        var payload = new OrderPlacedPayload(Guid.NewGuid(), 99.99m);
        var evt = new OrderPlacedEvent { OccurredOn = DateTimeOffset.UtcNow, Payload = payload };

        evt.Payload.Should().Be(payload);
        evt.Payload.OrderId.Should().Be(payload.OrderId);
        evt.Payload.Total.Should().Be(99.99m);
    }

    [Fact]
    public void DomainEventT_ImplementsIDomainEvent()
    {
        var evt = new OrderPlacedEvent
        {
            OccurredOn = DateTimeOffset.UtcNow,
            Payload = new OrderPlacedPayload(Guid.NewGuid(), 10m)
        };

        evt.Should().BeAssignableTo<IDomainEvent>();
    }

    [Fact]
    public void DomainEventT_Id_IsAutoGeneratedAndNonEmpty()
    {
        var evt = new OrderPlacedEvent
        {
            OccurredOn = DateTimeOffset.UtcNow,
            Payload = new OrderPlacedPayload(Guid.NewGuid(), 10m)
        };

        evt.Id.Should().NotBeEmpty();
    }

    [Fact]
    public void DomainEventT_OccurredOn_IsSuppliedViaInit()
    {
        var time = new DateTimeOffset(2026, 5, 26, 12, 0, 0, TimeSpan.Zero);
        var evt = new OrderPlacedEvent
        {
            OccurredOn = time,
            Payload = new OrderPlacedPayload(Guid.NewGuid(), 5m)
        };

        evt.OccurredOn.Should().Be(time);
    }

    [Fact]
    public void DomainEventT_ExtendsDomainEvent()
    {
        var evt = new OrderPlacedEvent
        {
            OccurredOn = DateTimeOffset.UtcNow,
            Payload = new OrderPlacedPayload(Guid.NewGuid(), 10m)
        };

        evt.Should().BeAssignableTo<DomainEvent>();
    }
}
