// Generates the package views that answer "which package do I reference, and what depends on what":
//
//   dotnet run eng/generate-package-index.cs            writes the files below
//   dotnet run eng/generate-package-index.cs -- --check fails (exit 1) when any of them is out of date
//
//   docs/packages.md                                     every packable package by tier, with the service
//                                                        project that references it and its SharedKernel deps
//   docs/dependency-graph.md                             Mermaid graphs: folders, then one graph per folder
//   eng/solution-filters/Platform.SharedKernel.{Tier}.slnf   one IDE view per tier (packages + their tests)
//
// Inputs are only what the build already enforces: each tracked .csproj's <SharedKernelTier>, <IsPackable>
// and ProjectReferences. Analyzer-only references (ReferenceOutputAssembly="false") are not dependencies.
// Output is deterministic and LF-terminated; --check ignores CR so a Windows checkout compares equal.

using System.Diagnostics;
using System.Text;
using System.Xml.Linq;

var check = args.Contains("--check");
var root = FindRepositoryRoot();

var tiers = new (string Name, string ReferenceFrom, string MayReference)[]
{
    ("Foundation", "any project", "Foundation"),
    ("Model", "the Domain project", "Foundation, Model"),
    ("Abstractions", "the Application project", "Foundation, Model, Abstractions"),
    ("Adapter", "the Infrastructure project", "Foundation, Model, Abstractions, declared adapter edges"),
    ("Host", "the Api / Worker project", "everything except Testing and Tooling"),
    ("Testing", "test projects only", "everything except Tooling"),
    ("Tooling", "the build (analyzers, architecture tests, linter)", "nothing"),
};

var projects = TrackedFiles(root, "*.csproj")
    .Select(path => ReadProject(root, path))
    .ToDictionary(p => p.FullPath, StringComparer.OrdinalIgnoreCase);

var packages = projects.Values
    .Where(p => p.Tier is not null && !string.Equals(p.IsPackable, "false", StringComparison.OrdinalIgnoreCase))
    .OrderBy(p => p.Name, StringComparer.Ordinal)
    .ToList();
var packageByPath = packages.ToDictionary(p => p.FullPath, StringComparer.OrdinalIgnoreCase);

List<Project> DependenciesOf(Project package) =>
    package.References
        .Where(packageByPath.ContainsKey)
        .Select(path => packageByPath[path])
        .OrderBy(p => p.Name, StringComparer.Ordinal)
        .ToList();

var outputs = new Dictionary<string, string>(StringComparer.Ordinal)
{
    ["docs/packages.md"] = PackagesMarkdown(),
    ["docs/dependency-graph.md"] = GraphMarkdown(),
};

var solutionProjects = SolutionProjects(Path.Combine(root, "Platform.SharedKernel.slnx"));
foreach (var tier in tiers)
{
    outputs[$"eng/solution-filters/Platform.SharedKernel.{tier.Name}.slnf"] = SolutionFilter(tier.Name);
}

var stale = new List<string>();
foreach (var (relative, content) in outputs)
{
    var path = Path.Combine(root, relative);
    var current = File.Exists(path) ? File.ReadAllText(path).Replace("\r", "") : null;
    if (current == content)
    {
        continue;
    }

    stale.Add(relative);
    if (!check)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }
}

if (check && stale.Count > 0)
{
    Console.Error.WriteLine("::error::Generated package views are out of date. Run: dotnet run eng/generate-package-index.cs");
    stale.ForEach(file => Console.Error.WriteLine($"  {file}"));
    return 1;
}

Console.WriteLine(check
    ? $"OK: {outputs.Count} generated package views are up to date ({packages.Count} packages)."
    : $"{stale.Count} of {outputs.Count} package views updated ({packages.Count} packages).");
return 0;

string PackagesMarkdown()
{
    var md = new StringBuilder();
    md.Append("# Package index\n\n");
    md.Append("> Generated by `eng/generate-package-index.cs` from each project's `<SharedKernelTier>` and `ProjectReference`s.\n");
    md.Append("> Do not edit by hand: run `dotnet run eng/generate-package-index.cs`. CI fails when this file is out of date.\n\n");
    md.Append($"{packages.Count} packages. The tier decides which project of a consuming service references a package; the build enforces it.\n\n");
    md.Append("| Tier | Reference it from | May reference | Packages |\n|---|---|---|---:|\n");
    foreach (var tier in tiers)
    {
        md.Append($"| [{tier.Name}](#{tier.Name.ToLowerInvariant()}) | {tier.ReferenceFrom} | {tier.MayReference} | {packages.Count(p => p.Tier == tier.Name)} |\n");
    }

    md.Append("\nSee also [dependency-graph.md](dependency-graph.md) and the per-tier solution filters in `eng/solution-filters/`.\n");

    foreach (var tier in tiers)
    {
        var inTier = packages.Where(p => p.Tier == tier.Name).ToList();
        if (inTier.Count == 0)
        {
            continue;
        }

        md.Append($"\n## {tier.Name}\n\nReference from {tier.ReferenceFrom}.\n\n");
        md.Append("| Package | Folder | SharedKernel dependencies |\n|---|---|---|\n");
        foreach (var package in inTier)
        {
            var dependencies = DependenciesOf(package);
            var dependencyText = dependencies.Count == 0 ? "—" : string.Join(", ", dependencies.Select(d => $"`{d.Name}`"));
            md.Append($"| [`{package.Name}`](../{package.Directory}/README.md) | `{package.Folder}` | {dependencyText} |\n");
        }
    }

    return md.ToString();
}

string GraphMarkdown()
{
    var md = new StringBuilder();
    md.Append("# Dependency graph\n\n");
    md.Append("> Generated by `eng/generate-package-index.cs` from `ProjectReference`s between packable projects.\n");
    md.Append("> Do not edit by hand: run `dotnet run eng/generate-package-index.cs`. CI fails when this file is out of date.\n\n");
    md.Append("An arrow `A --> B` means A references B. Tiers are listed in [packages.md](packages.md).\n\n");

    var folders = packages.Select(p => p.Folder).Distinct().OrderBy(f => f, StringComparer.Ordinal).ToList();

    md.Append("## Between folders\n\nEach arrow is labelled with the number of package references it stands for.\n\n");
    md.Append("```mermaid\nflowchart LR\n");
    foreach (var folder in folders)
    {
        md.Append($"  {NodeId(folder)}[\"{folder}\"]\n");
    }

    var folderEdges = packages
        .SelectMany(p => DependenciesOf(p).Select(d => (From: p.Folder, To: d.Folder)))
        .Where(e => e.From != e.To)
        .GroupBy(e => e)
        .OrderBy(g => g.Key.From, StringComparer.Ordinal)
        .ThenBy(g => g.Key.To, StringComparer.Ordinal);
    foreach (var edge in folderEdges)
    {
        md.Append($"  {NodeId(edge.Key.From)} -->|{edge.Count()}| {NodeId(edge.Key.To)}\n");
    }

    md.Append("```\n");

    foreach (var folder in folders)
    {
        var own = packages.Where(p => p.Folder == folder).ToList();
        var external = own.SelectMany(DependenciesOf).Where(d => d.Folder != folder)
            .DistinctBy(d => d.FullPath).OrderBy(d => d.Name, StringComparer.Ordinal).ToList();

        md.Append($"\n## {folder}\n\n```mermaid\nflowchart LR\n");
        md.Append($"  subgraph {NodeId("folder " + folder)}[\"{folder}\"]\n");
        foreach (var package in own)
        {
            md.Append($"    {NodeId(package.Name)}[\"{ShortName(package.Name)}<br/><i>{package.Tier}</i>\"]\n");
        }

        md.Append("  end\n");
        foreach (var package in external)
        {
            md.Append($"  {NodeId(package.Name)}([\"{ShortName(package.Name)}<br/><i>{package.Folder}</i>\"])\n");
        }

        foreach (var package in own)
        {
            foreach (var dependency in DependenciesOf(package))
            {
                md.Append($"  {NodeId(package.Name)} --> {NodeId(dependency.Name)}\n");
            }
        }

        md.Append("```\n");
    }

    return md.ToString();
}

string SolutionFilter(string tier)
{
    var included = new SortedSet<string>(StringComparer.Ordinal);
    foreach (var package in packages.Where(p => p.Tier == tier))
    {
        // The package and the projects nested in its folder (its .Tests project).
        foreach (var project in solutionProjects)
        {
            if (project == package.RelativePath || project.StartsWith(package.Directory + "/", StringComparison.Ordinal))
            {
                included.Add(project);
            }
        }
    }

    var json = new StringBuilder();
    json.Append("{\n  \"solution\": {\n    \"path\": \"../../Platform.SharedKernel.slnx\",\n    \"projects\": [\n");
    json.Append(string.Join(",\n", included.Select(p => $"      \"{p}\"")));
    json.Append("\n    ]\n  }\n}\n");
    return json.ToString();
}

static string ShortName(string name) => name.StartsWith("SharedKernel.", StringComparison.Ordinal) ? name["SharedKernel.".Length..] : name;

static string NodeId(string value) => new(value.Select(c => char.IsAsciiLetterOrDigit(c) ? c : '_').ToArray());

static Project ReadProject(string root, string relativePath)
{
    var fullPath = Path.GetFullPath(Path.Combine(root, relativePath));
    var document = XDocument.Load(fullPath);
    string? Property(string name) => document.Descendants(name).Select(e => e.Value.Trim()).LastOrDefault();

    var projectDirectory = Path.GetDirectoryName(fullPath)!;
    var references = document.Descendants("ProjectReference")
        .Where(r => !string.Equals((string?)r.Attribute("ReferenceOutputAssembly") ?? r.Element("ReferenceOutputAssembly")?.Value, "false", StringComparison.OrdinalIgnoreCase))
        .Select(r => (string?)r.Attribute("Include"))
        .Where(include => !string.IsNullOrWhiteSpace(include))
        .Select(include => Path.GetFullPath(Path.Combine(projectDirectory, include!.Replace('\\', Path.DirectorySeparatorChar))))
        .ToList();

    var directory = Path.GetDirectoryName(relativePath)!.Replace('\\', '/');
    var folder = Path.GetDirectoryName(directory)?.Replace('\\', '/');
    return new Project(
        Path.GetFileNameWithoutExtension(fullPath),
        fullPath,
        relativePath.Replace('\\', '/'),
        directory,
        string.IsNullOrEmpty(folder) ? "." : folder,
        Property("SharedKernelTier"),
        Property("IsPackable"),
        references);
}

static List<string> SolutionProjects(string slnx) =>
    XDocument.Load(slnx).Descendants("Project")
        .Select(p => ((string?)p.Attribute("Path"))?.Replace('\\', '/'))
        .Where(p => p is not null)
        .Select(p => p!)
        .ToList();

static List<string> TrackedFiles(string root, string pattern)
{
    var git = Process.Start(new ProcessStartInfo("git", $"ls-files -- \"{pattern}\"")
    {
        WorkingDirectory = root,
        RedirectStandardOutput = true,
        UseShellExecute = false,
    })!;
    var output = git.StandardOutput.ReadToEnd();
    git.WaitForExit();
    if (git.ExitCode != 0)
    {
        throw new InvalidOperationException("git ls-files failed.");
    }

    return output.Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
        .Where(path => !path.StartsWith("archive/", StringComparison.Ordinal))
        .ToList();
}

static string FindRepositoryRoot()
{
    for (var directory = new DirectoryInfo(Environment.CurrentDirectory); directory is not null; directory = directory.Parent)
    {
        if (File.Exists(Path.Combine(directory.FullName, "Platform.SharedKernel.slnx")))
        {
            return directory.FullName;
        }
    }

    throw new InvalidOperationException("Run from inside the repository (no Platform.SharedKernel.slnx found above the current directory).");
}

record Project(
    string Name,
    string FullPath,
    string RelativePath,
    string Directory,
    string Folder,
    string? Tier,
    string? IsPackable,
    List<string> References);
