using System.Collections.Concurrent;
using System.Data.Common;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using SharedKernel.Cryptography.Envelope;
using SharedKernel.Cryptography.KeyDerivation;
using SharedKernel.Persistence.EfCore.Encryption.Configuration;
using SharedKernel.Persistence.EfCore.Encryption.Diagnostics;

namespace SharedKernel.Persistence.EfCore.Encryption.TenantKeys;

/// <summary>
/// Per-tenant data keys: generated by the configured <see cref="IEnvelopeEncryptionProvider"/> (a KMS master key
/// wraps them), stored wrapped in the tenant key table, unwrapped on demand and cached for
/// <see cref="EncryptionOptions.TenantKeyCacheDuration"/>.
/// </summary>
/// <remarks>
/// Key rows are read and written on a separate connection (never the context's own, which may have a data reader
/// open while a row is materialized), so a key row created during a save is committed even if the business
/// transaction rolls back. That leaves at most an unused key, never data without a key.
/// </remarks>
internal sealed class TenantKeyStore
{
    internal const string TableName = "sk_tenant_encryption_keys";

    private readonly ConcurrentDictionary<Guid, TenantKeyEntry> _cache = new();
    private readonly Lazy<IEnvelopeEncryptionProvider> _envelope;
    private readonly EncryptionOptions _options;
    private readonly TimeProvider _timeProvider;
    private readonly ILogger<TenantKeyStore> _logger;

    public TenantKeyStore(
        IServiceProvider services,
        FieldEncryptionSettings settings,
        IOptions<EncryptionOptions> options,
        ILogger<TenantKeyStore> logger)
    {
        _options = options.Value;
        _timeProvider = services.GetService<TimeProvider>() ?? TimeProvider.System;
        _logger = logger;
        _envelope = new Lazy<IEnvelopeEncryptionProvider>(() =>
            settings.EnvelopeProviderFactory?.Invoke(services)
            ?? services.GetService<IEnvelopeEncryptionProvider>()
            ?? throw new InvalidOperationException(
                "Tenant data keys need an 'IEnvelopeEncryptionProvider' (a KMS master key that wraps them), for " +
                "example '.AddAzureKeyVaultEncryption(configuration)', or 'UseTenantDataKeys<TProvider>()'."));
        QualifiedTableName = QuoteTable(_options.TenantKeySchema);
    }

    /// <summary>The quoted, schema-qualified table name.</summary>
    public string QualifiedTableName { get; }

    /// <summary>Returns a fresh cached entry, or <see langword="null"/>.</summary>
    public TenantKeyEntry? TryGetCached(Guid tenantId) =>
        _cache.TryGetValue(tenantId, out var entry) && IsFresh(entry) ? entry : null;

    /// <summary>Loads (and, when <paramref name="create"/> is set, creates) the tenant's key, blocking the caller.</summary>
    /// <remarks>Used by the synchronous save and materialization paths on a cache miss only.</remarks>
    public TenantKeyEntry? GetBlocking(Guid tenantId, Func<CancellationToken, Task<DbConnection>> openConnection, bool create) =>
        TryGetCached(tenantId)
        ?? Task.Run(() => GetAsync(tenantId, openConnection, create, CancellationToken.None).AsTask()).GetAwaiter().GetResult();

    /// <summary>Loads (and, when <paramref name="create"/> is set, creates) the tenant's key.</summary>
    /// <returns>The entry, or <see langword="null"/> when the tenant has no key and <paramref name="create"/> is not set.</returns>
    public async ValueTask<TenantKeyEntry?> GetAsync(
        Guid tenantId,
        Func<CancellationToken, Task<DbConnection>> openConnection,
        bool create,
        CancellationToken cancellationToken)
    {
        if (TryGetCached(tenantId) is { } cached)
            return cached;

        var connection = await openConnection(cancellationToken).ConfigureAwait(false);
        await using (connection.ConfigureAwait(false))
        {
            var row = await ReadAsync(connection, tenantId, cancellationToken).ConfigureAwait(false);
            if (row is null && create)
            {
                using var dataKey = await _envelope.Value.GenerateDataKeyAsync(cancellationToken).ConfigureAwait(false);
                if (dataKey.PlaintextKey.Length < SubkeyDerivation.MinimumRootKeyLength)
                {
                    throw new CryptographicException(
                        $"The envelope provider generated a {dataKey.PlaintextKey.Length}-byte data key; tenant data keys need at least {SubkeyDerivation.MinimumRootKeyLength} bytes.");
                }

                await using var insert = connection.CreateCommand();
                insert.CommandText =
                    $"INSERT INTO {QualifiedTableName} (tenant_id, wrapped_key, master_key_id, created_at) " +
                    "VALUES (@tenant, @wrapped, @master, now()) ON CONFLICT (tenant_id) DO NOTHING";
                AddParameter(insert, "tenant", tenantId);
                AddParameter(insert, "wrapped", dataKey.WrappedKey.ToArray());
                AddParameter(insert, "master", dataKey.MasterKeyId);
                if (await insert.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false) == 1)
                    EncryptionLog.TenantKeyCreated(_logger, dataKey.MasterKeyId);

                // Re-read: when another process created the key first, its key wins and ours is discarded.
                row = await ReadAsync(connection, tenantId, cancellationToken).ConfigureAwait(false);
            }

            if (row is null)
                return null;

            TenantKeyEntry entry;
            if (row.Value.Shredded)
            {
                entry = new TenantKeyEntry(tenantId, null, _timeProvider.GetTimestamp());
            }
            else
            {
                var unwrapped = await _envelope.Value
                    .UnwrapDataKeyAsync(row.Value.WrappedKey!, row.Value.MasterKeyId!, cancellationToken)
                    .ConfigureAwait(false);
                if (unwrapped.IsFailure)
                {
                    throw new CryptographicException(
                        $"The tenant data key could not be unwrapped with master key '{row.Value.MasterKeyId}': {unwrapped.Error.Message}");
                }

                entry = new TenantKeyEntry(tenantId, unwrapped.Value, _timeProvider.GetTimestamp());
            }

            _cache[tenantId] = entry;
            return entry;
        }
    }

    /// <summary>Destroys the tenant's wrapped key, leaving a tombstone so the tenant is never given a new key.</summary>
    public async Task ShredAsync(Guid tenantId, DbConnection connection, DbTransaction transaction, CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.Transaction = transaction;
        command.CommandText =
            $"INSERT INTO {QualifiedTableName} AS k (tenant_id, wrapped_key, master_key_id, created_at, shredded_at) " +
            "VALUES (@tenant, NULL, NULL, now(), now()) ON CONFLICT (tenant_id) DO UPDATE " +
            "SET wrapped_key = NULL, master_key_id = NULL, shredded_at = COALESCE(k.shredded_at, now())";
        AddParameter(command, "tenant", tenantId);
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    /// <summary>Forgets this process's copy of the tenant's key and remembers it as shredded.</summary>
    public void MarkShredded(Guid tenantId)
    {
        if (_cache.TryGetValue(tenantId, out var previous))
            previous.Clear();

        _cache[tenantId] = new TenantKeyEntry(tenantId, null, _timeProvider.GetTimestamp());
    }

    /// <summary>The SQL that creates the tenant key table.</summary>
    internal static string CreateTableSql(string? schema)
    {
        var table = QuoteTable(schema);
        var schemaStatement = schema is null ? string.Empty : $"CREATE SCHEMA IF NOT EXISTS {Quote(schema)};\n";
        return schemaStatement +
            $"CREATE TABLE IF NOT EXISTS {table} (\n" +
            "    tenant_id uuid NOT NULL PRIMARY KEY,\n" +
            "    wrapped_key bytea NULL,\n" +
            "    master_key_id text NULL,\n" +
            "    created_at timestamptz NOT NULL DEFAULT now(),\n" +
            "    shredded_at timestamptz NULL,\n" +
            "    CONSTRAINT ck_sk_tenant_encryption_keys_state CHECK ((shredded_at IS NULL) = (wrapped_key IS NOT NULL AND master_key_id IS NOT NULL))\n" +
            ");";
    }

    private bool IsFresh(TenantKeyEntry entry) =>
        _timeProvider.GetElapsedTime(entry.LoadedTimestamp) < _options.TenantKeyCacheDuration;

    private async Task<(byte[]? WrappedKey, string? MasterKeyId, bool Shredded)?> ReadAsync(
        DbConnection connection, Guid tenantId, CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = $"SELECT wrapped_key, master_key_id, shredded_at IS NOT NULL FROM {QualifiedTableName} WHERE tenant_id = @tenant";
        AddParameter(command, "tenant", tenantId);
        await using var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
        if (!await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            return null;

        return (
            reader.IsDBNull(0) ? null : (byte[])reader.GetValue(0),
            reader.IsDBNull(1) ? null : reader.GetString(1),
            reader.GetBoolean(2));
    }

    private static string QuoteTable(string? schema) =>
        schema is null ? Quote(TableName) : $"{Quote(schema)}.{Quote(TableName)}";

    private static string Quote(string identifier) => "\"" + identifier.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";

    private static void AddParameter(DbCommand command, string name, object value)
    {
        var parameter = command.CreateParameter();
        parameter.ParameterName = name;
        parameter.Value = value;
        command.Parameters.Add(parameter);
    }
}

/// <summary>One tenant's unwrapped data key and the per-purpose keys derived from it.</summary>
internal sealed class TenantKeyEntry(Guid tenantId, byte[]? key, long loadedTimestamp)
{
    private readonly ConcurrentDictionary<string, byte[]> _derived = new(StringComparer.Ordinal);
    private byte[]? _key = key;

    public Guid TenantId { get; } = tenantId;

    public long LoadedTimestamp { get; } = loadedTimestamp;

    public bool IsShredded => _key is null;

    /// <summary>The key id stored in every payload encrypted with this tenant's key.</summary>
    public string KeyId => TenantKeyIds.For(TenantId);

    public byte[] Derive(string purpose)
    {
        var key = _key ?? throw new TenantKeyShreddedException();
        return _derived.GetOrAdd(purpose, static (p, material) =>
            SubkeyDerivation.DeriveKey(material, "sk.persistence.field-encryption", Encoding.UTF8.GetBytes(p)), key);
    }

    public void Clear()
    {
        if (_key is { } key)
            CryptographicOperations.ZeroMemory(key);
        foreach (var derived in _derived.Values)
            CryptographicOperations.ZeroMemory(derived);
        _derived.Clear();
        _key = null;
    }
}

/// <summary>The key-id format of tenant data keys inside encrypted payloads: <c>skt:{tenant id, 32 hex digits}</c>.</summary>
internal static class TenantKeyIds
{
    private const string Prefix = "skt:";

    public static string For(Guid tenantId) => Prefix + tenantId.ToString("N");

    public static bool TryParse(string keyId, out Guid tenantId)
    {
        tenantId = Guid.Empty;
        return keyId.StartsWith(Prefix, StringComparison.Ordinal)
            && Guid.TryParseExact(keyId.AsSpan(Prefix.Length), "N", out tenantId);
    }
}
